// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ouhpdpzfopaqbfosptuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91aHBkcHpmb3BhcWJmb3NwdHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwODYzNjcsImV4cCI6MjA3ODY2MjM2N30.FrOfUam70t9aPJyfXHp6_iry9sxeM52-hQ6W74_DaQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);